services:

  db:
    image: postgres:15
    container_name: postgresql
    environment:
      POSTGRES_DB: cloud_service
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cloud_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_LIQUIBASE_ENABLED=true
    depends_on:
      - db
#    volumes:
#      - ./uploads:/app/uploads

volumes:
  postgres_data:
#  uploads: